# permissions for end users to edit fabrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabric-editor-role
rules:
- apiGroups:
  - networking.m3l.dev
  resources:
  - fabrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.m3l.dev
  resources:
  - fabrics/status
  verbs:
  - get
