apiVersion: networking.m3l.dev/v1alpha1
kind: Fabric
metadata:
  name: internal
spec:
  ipv4:
    # If this is set, the Fabric will be in Gateway Mode.
    dhcp:
      # Whether to enable the DHCP client or not.
      client: false
      # The settings below control the behavior of the
      # DHCP server.
      subnet: 172.16.0.0/22
      start: 172.16.0.1
      end: 172.16.3.200
    # Required to be set by the user if the DHCP server in
    # the Fabric is enabled.
    gateway: 172.16.3.254
    # The IP addresses of the router on this network edge.
    addresses:
      - 172.16.3.254/22
    nameservers:
      addresses:
        - 1.1.1.1
        - 1.0.0.1
  router:
    hostname: dfrobot-cm4rt
    vlan: 1
    interfaces:
      - name: eth0
        mac: de:ad:be:ef:00:01
      - name: eth1
        mac: de:ad:be:ef:00:02
    bondingMode: 802.3ad
  # TODO: Define IPV6 configuration layout.
  # TODO: Add configuration for PXE booting and Tinkerbell.
---
apiVersion: networking.m3l.dev/v1alpha1
kind: Fabric
metadata:
  name: external
spec:
  ipv4:
    dhcp:
      client: true
  router:
    hostname: netgear-gs748t
    vlan: 4093
    interfaces:
      - name: eth0
        mac: be:ee:ee:ef:00:01
  # TODO: Define IPV6 configuration layout.
  # TODO: Add configuration for PXE booting and Tinkerbell.
---

